version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - VITE_DB_HOST=db
      - VITE_DB_PORT=5432
      - VITE_DB_USER=postgres
      - VITE_DB_PASSWORD=postgres
      - VITE_DB_NAME=municipios
    networks:
      - app-network

  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=municipios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge