/*
  # Create initial database schema

  1. Tables
    - spatial_ref_sys: PostGIS spatial reference system table
    - municipios: Stores municipality geometries and metadata
    - div_territorial_zonas: Stores territorial division information
    - divterritorialdepto_determinantes: Stores department determinants
    - divterritorialmuni_determinantes: Stores municipality determinants
    - indicadores_territorial: Stores territorial indicators

  2. Extensions
    - PostGIS for spatial data support
*/

-- Enable PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- Create spatial_ref_sys table if it doesn't exist
CREATE TABLE IF NOT EXISTS spatial_ref_sys (
    srid INTEGER NOT NULL PRIMARY KEY,
    auth_name VARCHAR(256),
    auth_srid INTEGER,
    srtext VARCHAR(2048),
    proj4text VARCHAR(2048),
    CONSTRAINT spatial_ref_sys_srid_check CHECK (srid > 0 AND srid <= 998999)
);

-- Create municipios table
CREATE TABLE IF NOT EXISTS municipios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    geom GEOMETRY(MultiPolygon, 4326) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    id_grilla INTEGER
);

-- Create div_territorial_zonas table
CREATE TABLE IF NOT EXISTS div_territorial_zonas (
    nc INTEGER PRIMARY KEY,
    dpto_ccdgo TEXT NOT NULL,
    dpto_cnmbr TEXT NOT NULL,
    mpio_cdpmp TEXT NOT NULL,
    mpio_cnmbr TEXT NOT NULL,
    id_grilla INTEGER NOT NULL,
    caribe BOOLEAN NOT NULL,
    andina BOOLEAN NOT NULL,
    amazonia BOOLEAN NOT NULL,
    orinoquia BOOLEAN NOT NULL,
    pacifica BOOLEAN NOT NULL,
    insular BOOLEAN NOT NULL,
    estructura_1 BOOLEAN NOT NULL,
    estructura_2 BOOLEAN NOT NULL,
    estructura_3 BOOLEAN NOT NULL,
    pais BOOLEAN NOT NULL,
    zomac BOOLEAN NOT NULL,
    pdet BOOLEAN NOT NULL
);

-- Create divterritorialdepto_determinantes table
CREATE TABLE IF NOT EXISTS divterritorialdepto_determinantes (
    dpto_ccdgo INTEGER PRIMARY KEY,
    dpto_cnmbr TEXT,
    suma_s_111 INTEGER,
    suma_s_112 INTEGER,
    suma_s_113 INTEGER,
    suma_s_114 INTEGER,
    suma_s_115 INTEGER,
    suma_s_121 INTEGER,
    suma_s_122 INTEGER,
    suma_s_123 INTEGER,
    suma_s_131 INTEGER,
    suma_s_132 INTEGER,
    suma_s_141 INTEGER,
    suma_s_151 INTEGER,
    suma_s_161 INTEGER,
    suma_s_162 INTEGER,
    suma_s_163 INTEGER,
    suma_s_164 INTEGER,
    suma_a_221 INTEGER,
    suma_a_222 INTEGER,
    suma_a_223 INTEGER,
    suma_a_231 INTEGER,
    suma_a_241 INTEGER,
    suma_a_242 INTEGER,
    suma_a_243 INTEGER,
    suma_a_244 INTEGER,
    suma_a_245 INTEGER,
    suma_a_251 INTEGER,
    suma_a_252 INTEGER,
    suma_a_211 INTEGER,
    suma_t_311 INTEGER,
    suma_t_312 INTEGER,
    suma_t_313 INTEGER,
    suma_t_321 INTEGER,
    suma_t_322 INTEGER,
    suma_t_331 INTEGER,
    suma_t_332 INTEGER,
    suma_t_333 INTEGER,
    suma_t_334 INTEGER,
    suma_t_335 INTEGER,
    suma_n_411 INTEGER,
    suma_n_421 INTEGER,
    suma_n_431 INTEGER,
    suma_n_441 INTEGER,
    suma_n_412 INTEGER,
    caribe BOOLEAN,
    andina BOOLEAN,
    amazonia BOOLEAN,
    orinoquia BOOLEAN,
    pacifica BOOLEAN,
    insular BOOLEAN,
    estructura_1 BOOLEAN,
    estructura_2 BOOLEAN,
    estructura_3 BOOLEAN,
    pais BOOLEAN
);

-- Create divterritorialmuni_determinantes table
CREATE TABLE IF NOT EXISTS divterritorialmuni_determinantes (
    mpio_cdpmp VARCHAR(10) PRIMARY KEY,
    mpio_cnmbr VARCHAR(100) NOT NULL,
    suma_s_111 INTEGER DEFAULT 0,
    suma_s_112 INTEGER DEFAULT 0,
    suma_s_113 INTEGER DEFAULT 0,
    suma_s_114 INTEGER DEFAULT 0,
    suma_s_115 INTEGER DEFAULT 0,
    suma_s_121 INTEGER DEFAULT 0,
    suma_s_122 INTEGER DEFAULT 0,
    suma_s_123 INTEGER DEFAULT 0,
    suma_s_131 INTEGER DEFAULT 0,
    suma_s_132 INTEGER DEFAULT 0,
    suma_s_141 INTEGER DEFAULT 0,
    suma_s_151 INTEGER DEFAULT 0,
    suma_s_161 INTEGER DEFAULT 0,
    suma_s_162 INTEGER DEFAULT 0,
    suma_s_163 INTEGER DEFAULT 0,
    suma_s_164 INTEGER DEFAULT 0,
    suma_a_221 INTEGER DEFAULT 0,
    suma_a_222 INTEGER DEFAULT 0,
    suma_a_223 INTEGER DEFAULT 0,
    suma_a_231 INTEGER DEFAULT 0,
    suma_a_241 INTEGER DEFAULT 0,
    suma_a_242 INTEGER DEFAULT 0,
    suma_a_243 INTEGER DEFAULT 0,
    suma_a_244 INTEGER DEFAULT 0,
    suma_a_245 INTEGER DEFAULT 0,
    suma_a_251 INTEGER DEFAULT 0,
    suma_a_252 INTEGER DEFAULT 0,
    suma_a_211 INTEGER DEFAULT 0,
    suma_t_311 INTEGER DEFAULT 0,
    suma_t_312 INTEGER DEFAULT 0,
    suma_t_313 INTEGER DEFAULT 0,
    suma_t_321 INTEGER DEFAULT 0,
    suma_t_322 INTEGER DEFAULT 0,
    suma_t_331 INTEGER DEFAULT 0,
    suma_t_332 INTEGER DEFAULT 0,
    suma_t_333 INTEGER DEFAULT 0,
    suma_t_334 INTEGER DEFAULT 0,
    suma_t_335 INTEGER DEFAULT 0,
    suma_n_411 INTEGER DEFAULT 0,
    suma_n_421 INTEGER DEFAULT 0,
    suma_n_431 INTEGER DEFAULT 0,
    suma_n_441 INTEGER DEFAULT 0,
    suma_n_412 INTEGER DEFAULT 0
);

-- Create indicadores_territorial table
CREATE TABLE IF NOT EXISTS indicadores_territorial (
    dpto_ccdgo INTEGER NOT NULL,
    dpto_cnmbr VARCHAR(100),
    mpio_cdpmp INTEGER NOT NULL,
    mpio_cnmbr VARCHAR(100),
    pobl_rur INTEGER,
    anno_pobl_rur INTEGER,
    pobl_urb INTEGER,
    anno_pobl_urb INTEGER,
    pobl_tot INTEGER,
    anno_pobl_tot INTEGER,
    nbi DOUBLE PRECISION,
    anno_nbi INTEGER,
    ipm DOUBLE PRECISION,
    anno_ipm INTEGER,
    icee_cm DOUBLE PRECISION,
    anno_icee_cm INTEGER,
    icee_resto DOUBLE PRECISION,
    anno_icee_resto INTEGER,
    icee_tot DOUBLE PRECISION,
    anno_icee_tot INTEGER,
    di_p_nal DOUBLE PRECISION,
    anno_di_p_nal INTEGER,
    indesarrollo_mun DOUBLE PRECISION,
    anno_indesarrollo_mun INTEGER,
    cob_gres_efec DOUBLE PRECISION,
    anno_cob_gres_efec INTEGER,
    pibxhabitante DOUBLE PRECISION,
    anno_pibxhabitante INTEGER,
    actividades_primarias DOUBLE PRECISION,
    anno_actividades_primarias INTEGER,
    actividades_secundarias DOUBLE PRECISION,
    anno_actividades_secundarias INTEGER,
    actividades_terciarias DOUBLE PRECISION,
    anno_actividades_terciarias INTEGER,
    sumatoria_actividades DOUBLE PRECISION,
    anno_sumatoria_actividades INTEGER,
    proporción_para_el_dpto DOUBLE PRECISION,
    anno_proporción_para_el_dpto INTEGER,
    pobreza_monetaria_extrema DOUBLE PRECISION,
    anno_pobreza_monetaria_extrema INTEGER,
    homicidios_x_cada_100000_habitantes DOUBLE PRECISION,
    anno_homicidios_x_cada_100000_habitantes INTEGER,
    cobertura_de_alcantarillado DOUBLE PRECISION,
    anno_cobertura_de_alcantarillado INTEGER,
    cobertura_de_acueducto DOUBLE PRECISION,
    anno_cobertura_de_acueducto INTEGER,
    poblacion_en_condicion_de_miseria DOUBLE PRECISION,
    anno_poblacion_en_condicion_de_miseria INTEGER,
    di_p_nal_norm DOUBLE PRECISION,
    pobl_rur_pct DOUBLE PRECISION,
    pobl_rurt_pct DOUBLE PRECISION,
    pobl_urb_pct DOUBLE PRECISION,
    pobl_tott_pct DOUBLE PRECISION,
    di_p_dep DOUBLE PRECISION,
    a_km2 DOUBLE PRECISION,
    rank_dep_pobl_rur INTEGER,
    rank_dep_pobl_urb INTEGER,
    rank_dep_pobl_tot INTEGER,
    rank_dep_nbi INTEGER,
    rank_dep_ipm INTEGER,
    rank_dep_icee_cm INTEGER,
    rank_dep_icee_resto INTEGER,
    rank_dep_icee_tot INTEGER,
    rank_dep_indesarrollo_mun INTEGER,
    rank_dep_cob_gres_efec INTEGER,
    rank_dep_actividades_primarias INTEGER,
    rank_dep_actividades_secundarias INTEGER,
    rank_dep_actividades_terciarias INTEGER,
    rank_dep_sumatoria_actividades INTEGER,
    rank_dep_proporcion_para_el_dpto INTEGER,
    rank_dep_homicidios_x_cada_100000_habitantes INTEGER,
    rank_dep_cobertura_de_alcantarillado INTEGER,
    rank_dep_cobertura_de_acueducto INTEGER,
    rank_dep_poblacion_en_condicion_de_miseria INTEGER,
    rank_dep_a_km2 INTEGER,
    rank_nac_pobl_rur INTEGER,
    rank_nac_pobl_urb INTEGER,
    rank_nac_pobl_tot INTEGER,
    rank_nac_nbi INTEGER,
    rank_nac_ipm INTEGER,
    rank_nac_icee_cm INTEGER,
    rank_nac_icee_resto INTEGER,
    rank_nac_icee_tot INTEGER,
    rank_nac_indesarrollo_mun INTEGER,
    rank_nac_cob_gres_efec INTEGER,
    rank_nac_pibxhabitante INTEGER,
    rank_nac_actividades_primarias INTEGER,
    rank_nac_actividades_secundarias INTEGER,
    rank_nac_actividades_terciarias INTEGER,
    rank_nac_sumatoria_actividades INTEGER,
    rank_nac_proporcion_para_el_dpto INTEGER,
    rank_nac_pobreza_monetaria_extrema INTEGER,
    rank_nac_homicidios_x_cada_100000_habitantes INTEGER,
    rank_nac_cobertura_de_alcantarillado INTEGER,
    rank_nac_cobertura_de_acueducto INTEGER,
    rank_nac_poblacion_en_condicion_de_miseria INTEGER,
    rank_nac_a_km2 INTEGER,
    PRIMARY KEY (dpto_ccdgo, mpio_cdpmp)
);